### ISSUE TITLE
Dash in directive name causes panic

### ISSUE THREAD

**Issue by dpetersen** [caddyserver/caddyext#2]
I probably shouldn't be putting dashes in my directive names, but when I did a `caddext install my-dashed-name:example.com/path/to/directive` it installed correctly, but the next `caddy stack` command panicked with:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4aabac]

goroutine 1 [running]:
github.com/caddyserver/caddyext/directives.(*DirectiveList).LoadList(0xc8200150b0, 0x0, 0x0)
        /home/dev/gopath/src/github.com/caddyserver/caddyext/directives/directives.go:190 +0x104c
github.com/caddyserver/caddyext/directives.NewFrom(0xc820010540, 0x3f, 0x0, 0x0, 0x0, 0x0)
        /home/dev/gopath/src/github.com/caddyserver/caddyext/directives/directives.go:40 +0x14e
github.com/caddyserver/caddyext/commands.StackExtension(0xa70080, 0xa98ef8, 0x0, 0x0)
        /home/dev/gopath/src/github.com/caddyserver/caddyext/commands/stack.go:22 +0x101
github.com/spf13/cobra.(*Command).execute(0xa70080, 0xa98ef8, 0x0, 0x0, 0x0, 0x0)
        /home/dev/gopath/src/github.com/spf13/cobra/command.go:569 +0x869
github.com/spf13/cobra.(*Command).ExecuteC(0xa6f280, 0xa70080, 0x0, 0x0)
        /home/dev/gopath/src/github.com/spf13/cobra/command.go:656 +0x56b
github.com/spf13/cobra.(*Command).Execute(0xa6f280, 0x0, 0x0)
        /home/dev/gopath/src/github.com/spf13/cobra/command.go:615 +0x2d
github.com/caddyserver/caddyext/commands.Execute()
        /home/dev/gopath/src/github.com/caddyserver/caddyext/commands/commands.go:58 +0xacb
main.main()
        /home/dev/gopath/src/github.com/caddyserver/caddyext/main.go:6 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
```

I've stopped using dashes, but this might help somebody in the future.

**Comment by mholt** [comment]
Good to know... somebody want to take a look at this?

In the meantime don't use dashes I guess :smile:

**Comment by pedronasser** [comment]
I'll take a look on that.
